import type { Metadata } from "next"
import Navbar from "./components/Navbar"
import { SessionProvider } from "next-auth/react"
import "./globals.css"

export const metadata: Metadata = {
  title: "Crapperoni Auth",
  description: "Generated by Luigi",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  )
}
